image: php:8.0

common: &common
  step:
    name: Tests
    caches:
      - composer
    script:
      - apt-get update && apt-get install -y wget git zip unzip sqlite3 libpng-dev libjpeg-dev zlib1g-dev libzip-dev libxml2-dev libnss3 libmcrypt-dev libfreetype6-dev libjpeg62-turbo-dev
      - docker-php-ext-install zip gd soap pcntl bcmath pdo_mysql
      - docker-php-ext-configure gd --with-freetype --with-jpeg
      - docker-php-ext-install -j$(nproc) gd
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer # Install Composer
      - composer -V
      - composer install --ignore-platform-reqs
      - php -r "file_exists('.env') || copy('.env.example', '.env');"
      - php artisan migrate --force
      - php artisan key:generate # Generate a key via Artisan
      #- vendor/bin/phpunit -d memory_limit=1024M --no-coverage # Run tests
    services:
      - mysql

pipelines:

  branches:
    master:
      - <<: *common
      - step:
          name: Deploy to master
          deployment: Production
          script:
            - apt-get update && apt-get install -y unzip wget
            - wget -q --spider https://forge.laravel.com/servers/466621/sites/1342660/deploy/http?token=x7H4snM7g0jFIqBi2Ob0nETwJLYoLuFaodU4NicG
    dev:
      - <<: *common
      - step:
          name: Deploy to development
          script:
            - apt-get update && apt-get install -y unzip wget
            - wget -q --spider https://forge.laravel.com/servers/454109/sites/1354396/deploy/http?token=IgQr1SbYEOjWDl8aVcbEqotX3Dw3poKJfRJKrwFQ

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'
